# Uncomment the next line to define a global platform for your project
platform :ios, '10.3'

target 'Seabird' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  use_frameworks!

  # Pods for Seabird
  pod 'Firebase/Core'
#  pod 'Firebase/Analytics'
#  pod 'Firebase/Auth'
#  pod 'Firebase/Database'
#  pod 'Firebase/Crash'
#  pod 'Firebase/Storage'

#  target 'SeabirdTests' do
#    inherit! :search_paths
#    # Pods for testing
##    pod 'GoogleAnalytics'
##    pod 'Firebase/Analytics'
#  end

end
